[package]
name = "inth-oauth2"
version = "0.8.0"

description = "OAuth2 client"
keywords = ["authentication", "authorization", "auth", "oauth"]

authors = ["Curtis McEnroe <programble@gmail.com>"]
license = "ISC"

documentation = "https://cmcenroe.me/inth-oauth2/inth_oauth2"
repository = "https://github.com/programble/inth-oauth2"
readme = "README.md"

[features]
default = ["serde"]

[dependencies]
chrono = "0.2.17"
hyper = "0.7.0"
rustc-serialize = "0.3.16"
url = "0.5.0"

[dependencies.serde]
version = "0.7.0"
optional = true

[dev-dependencies]
serde_json = "0.7.0"
yup-hyper-mock = "1.3.2"
